# Generated by Django 5.2 on 2026-06-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_cleanup_historical_fitnessclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfitnessclass',
            name='club',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='club',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='club',
        ),
        migrations.RemoveField(
            model_name='historicalclub',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalclub',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalclub',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='HistoricalClub',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
